### ISSUE TITLE
[NAV] cg_look -g path2file: Unhandled Python exception

### ISSUE THREAD

**Issue by fuhrmanj** [pyCGNS/pyCGNS#139] opened 2023-01-31 15:53 UTC
MacOS 12.6.2
Python version 3.7.16 via conda (conda create --name env_name python=3.7)
pyCGNS version 6.1.4
HDF5 Version: 1.10.6

Issue is also present on windows via anaconda installation (conda install -c conda-forge pycgns)

cg_look -g path2file throws error: Unhandled Python exception.

I think I was able to track the line of code: 
Line 66 in CGNS/NAV/wcontrol.py: QW.control_log = MSG.Q7Log().
The error is: QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)

Any ideas? Please let me know, if you need more information. Thanks in advance!

**Comment by MicK7** [comment] 2023-02-01 06:24
Thanks for the report. It seems like there is a bad interaction between the main GUI and an other thread.
This need more investigation

**Comment by fuhrmanj** [comment] 2023-02-01 08:43
Have you been able to reproduce the error? Because I was not able to open any cgns files in VTK view, even the example ones from the main cgns website (https://cgns.github.io/CGNSFiles.html). Thanks for looking into it.

**Comment by MicK7** [comment] 2023-02-01 12:52
Hello, could you run 

cg_look **-v** -g path2file

with pycgns v6.2.1 please.

It would be nice to reproduce the error with this last version.

**Comment by fuhrmanj** [comment] 2023-02-01 15:11
On my Linux machine:

cg_look -v sqnz_s.hdf.cgns 
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
\### cg_look: start
\### cg_look: loading: [sqnz_s.hdf.cgns]
Traceback (most recent call last):
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.1-py3.7-linux-x86_64.egg/CGNS/NAV/wtree.py", line 922, in vtkview
    from .wvtk import Q7VTK
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.1-py3.7-linux-x86_64.egg/CGNS/NAV/wvtk.py", line 21, in <module>
    from .Q7VTKWindow import Ui_Q7VTKWindow
  File "CGNS/NAV/G/Q7VTKWindow.pyx", line 419, in init Q7VTKWindow
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.1-py3.7-linux-x86_64.egg/CGNS/NAV/Q7VTKRenderWindowInteractor.py", line 68, in <module>
    from vtkmodules.vtkRenderingUI import vtkGenericRenderWindowInteractor
ModuleNotFoundError: No module named 'vtkmodules.vtkRenderingUI'
Aborted (core dumped)

**Comment by fuhrmanj** [comment] 2023-02-01 15:15
And in windows
 cg_look -v -g .\Case1.cgn
\### cg_look: start
\### cg_look: loading: [.\Case1.cgn]
Traceback (most recent call last):
  File "C:\Users\fuhrmanj\iRIC\Miniconda3\envs\cgns\lib\site-packages\CGNS\NAV\wcontrol.py", line 436, in loadCompleted
    child = self.loadQ7Tree(fgprint)
  File "C:\Users\fuhrmanj\iRIC\Miniconda3\envs\cgns\lib\site-packages\CGNS\NAV\wcontrol.py", line 508, in loadQ7Tree
    return Q7Tree(self, "/", fgprint.index)
  File "C:\Users\fuhrmanj\iRIC\Miniconda3\envs\cgns\lib\site-packages\CGNS\NAV\wtree.py", line 273, in __init__
    self.vtkview()
  File "C:\Users\fuhrmanj\iRIC\Miniconda3\envs\cgns\lib\site-packages\CGNS\NAV\wtree.py", line 922, in vtkview
    from CGNS.NAV.wvtk import Q7VTK
  File "C:\Users\fuhrmanj\iRIC\Miniconda3\envs\cgns\lib\site-packages\CGNS\NAV\wvtk.py", line 21, in <module>
    from CGNS.NAV.Q7VTKWindow import Ui_Q7VTKWindow
  File "CGNS\NAV\G\Q7VTKWindow.pyx", line 419, in init Q7VTKWindow
ImportError: cannot import name Q7VTKRenderWindowInteractor

**Comment by fuhrmanj** [comment] 2023-02-01 15:39
On my MacBook:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.1.4-py3.7-macosx-10.9-x86_64.egg/CGNS/NAV/wtree.py", line 922, in vtkview
    from CGNS.NAV.wvtk import Q7VTK
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.1.4-py3.7-macosx-10.9-x86_64.egg/CGNS/NAV/wvtk.py", line 21, in <module>
    from CGNS.NAV.Q7VTKWindow import Ui_Q7VTKWindow
  File "CGNS/NAV/G/Q7VTKWindow.pyx", line 417, in init Q7VTKWindow
ImportError: cannot import name Q7VTKRenderWindowInteractor

**Comment by MicK7** [comment] 2023-02-02 13:09
Thanks for the feedback. 
Hello, could you run again

cg_look -v -g path2file

against pycgns v6.2.2 please.

I can't reproduce the error with windows.

**Comment by fuhrmanj** [comment] 2023-02-02 17:33
cg_look -v -g Downloads/sqnz_s.hdf.cgns 
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
### cg_look: start
### cg_look: loading: [Downloads/sqnz_s.hdf.cgns]
Traceback (most recent call last):
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wcontrol.py", line 436, in loadCompleted
    child = self.loadQ7Tree(fgprint)
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wcontrol.py", line 508, in loadQ7Tree
    return Q7Tree(self, "/", fgprint.index)
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wtree.py", line 273, in __init__
    self.vtkview()
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wtree.py", line 922, in vtkview
    from .wvtk import Q7VTK
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wvtk.py", line 21, in <module>
    from .Q7VTKWindow import Ui_Q7VTKWindow
  File "CGNS/NAV/G/Q7VTKWindow.pyx", line 419, in init Q7VTKWindow
  File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/Q7VTKRenderWindowInteractor.py", line 68, in <module>
    from vtkmodules.vtkRenderingUI import vtkGenericRenderWindowInteractor
ModuleNotFoundError: No module named 'vtkmodules.vtkRenderingUI'

**Comment by MicK7** [comment] 2023-02-02 17:43
> cg_look -v -g Downloads/sqnz_s.hdf.cgns libGL error: No matching fbConfigs or visuals found libGL error: failed to load driver: swrast ### cg_look: start ### cg_look: loading: [Downloads/sqnz_s.hdf.cgns] Traceback (most recent call last): File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wcontrol.py", line 436, in loadCompleted child = self.loadQ7Tree(fgprint) File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wcontrol.py", line 508, in loadQ7Tree return Q7Tree(self, "/", fgprint.index) File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wtree.py", line 273, in **init** self.vtkview() File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wtree.py", line 922, in vtkview from .wvtk import Q7VTK File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/wvtk.py", line 21, in from .Q7VTKWindow import Ui_Q7VTKWindow File "CGNS/NAV/G/Q7VTKWindow.pyx", line 419, in init Q7VTKWindow File "/home/fuhrmanj/anaconda3/envs/cgns/lib/python3.7/site-packages/pyCGNS-6.2.2-py3.7-linux-x86_64.egg/CGNS/NAV/Q7VTKRenderWindowInteractor.py", line 68, in from vtkmodules.vtkRenderingUI import vtkGenericRenderWindowInteractor ModuleNotFoundError: No module named 'vtkmodules.vtkRenderingUI'

It looks like a bug with the conda environment. Have you tested on windows or osx ?

**Comment by fuhrmanj** [comment] 2023-02-03 11:10
on Ubuntu

**Comment by MicK7** [comment] 2023-02-03 12:59
Can we close this ticket on macos and open a new one for linux/ubuntu ?

**Closed** 2023-02-04 00:42 UTC
Labels: bug
